apiVersion: v1
kind: Service
metadata:
  name: hello-ci-cd-svc
spec:
  type: NodePort
  selector:
    app: hello-ci-cd
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
